### ISSUE TITLE
Most recent version does not work with physical keyboard

### ISSUE THREAD

**Issue by aaronrolls** [deadlyjack/code-editor#81]
After updating to the most recent version, 1.1.14.119 I can no longer use my physical keyboard to type anything. I am using a nexdock with a samsung note 10 in dex mode. The screen keyboard works fine.

**Comment by deadlyjack** [comment]
Sorry, It was my mistake. I accidentally pushed update without testing Acode with external keyboard. I've fixed it and update will be available soon. Sorry for the inconvenience.

**Comment by mberasategi** [comment]
Any updates on this? I mostly use the physical keyboard precisely for code/plain text writing... I have also tried version 1.1.14.131 from the website but it's still not working. Thanks for the great work!
